spring:
  application:
    name: server
  datasource:
    url: jdbc:sqlite:database.db
    driver-class-name: org.sqlite.JDBC

server:
  port: 10635

log-pattern: "%d{yy-MM-dd' 'HH:mm:ss.SSS} [%-5level] [%15.15t] [%40.40c{39}:%4.4L] - %m%n"

logging:
  level:
    kot.gin: debug
  pattern:
    console: ${log-pattern}
    file: ${log-pattern}
  file:
    path: ./logs


auto-table:
  # 运行模式：none | validate | create | update（默认）
  mode: update
  # 是否显示 banner
  show-banner: true
  # 自动删除实体中不存在的字段（谨慎开启）
  auto-drop-column: false
  strict-extends: false

mybatis-plus:
  type-handlers-package: kot.gin.hentai_dashboard.server.modules.base.handler